apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: public
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: public.efca1e6.kyma.shoot.live.k8s-hana.ondemand.com
    name: number-generator
    port: 8017